### PR TITLE
feat: change color, text and logo for rebranding

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Comment by anehx** [comment]
1. Why isn't the update a separate PR?
2. You're aware that 3.12 is not the current LTS, right?

**Comment by Yelinz** [comment]
> 
> 
>     1. Why isn't the update a separate PR?
> 
>     2. You're aware that 3.12 is not the current LTS, right?

1. Forgot to switch branches, ill move the update
2. Yes, but 3.12 is still an active lts

**Comment by anehx** [comment]
Sure it is but why not upgrade to the current if you're doing an upgrade anyway??

**Comment by Yelinz** [comment]
I did the update mostly because i saw it was on 3.10 which isnt even an lts and just took it to the next one

**Comment by anehx** [comment]
Are you aware that the version defined in the `package.json` here is just the version of the dummy app? The relevant version would be the scenarios which are run in the CI

**Comment by Yelinz** [comment]
No I wasn't aware of that

**Pull request merged**
